version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: chore(ci)
    labels: ['skip changelog']

  # Rust
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: monthly
    groups:
      rust-crates:
        patterns:
          - "*"
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: chore(rust)
      prefix-development: chore(rust)
    labels: ['skip changelog']

  # Python
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    groups:
      python-packages:
        patterns:
          - "*"
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: chore(python)
    labels: ['skip changelog']

  # Documentation
  - package-ecosystem: pip
    directory: docs
    schedule:
      interval: monthly
    groups:
      python-packages:
        patterns:
          - "*"
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: chore(python)
    labels: ['skip changelog']