[package]
name = "rustAnalyser"
version = "0.1.0"
edition = "2018"

[lib]
name = "rustAnalyser"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.11.0"
hdf5 = "0.7.0"
ndarray = "0.13"
ndarray-linalg = "0.12"
[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
