[package]
name = "upppp_rust"
version = "0.1.0"
authors = ["Dominik Werner, Daniel Weston"]
edition = "2021"

[lib]
name = "upppp_rust"
crate-type = ["cdylib", "rlib"]

# TODO consider using thiserror for error handling
[dependencies]
anyhow = "1.0.94"
colorous = "1.0.15"
csv = "1.3.1"
derive-getters = "0.5.0"
dyn-clone = "1.0"
# hdf5 = { version = "0.8.1" }#, features = ["blosc"]}
hdf5 = { package = "hdf5-metno", git = "https://github.com/metno/hdf5-rust.git" }
indicatif = "0.18.0"
itertools = "0.14.0"
natord = "1.0.9"
ndarray = "0.16.1"
ndarray-csv = { version = "0.5.1" }
ndarray-stats = "0.6.0"
num-traits = "0.2.14"
numpy = "0.23.0"
plotly = { version = "0.13.5", features = ["plotly_embed_js"] }
# plotly = { git = "https://github.com/DanW97/plotly.git" }
polyfit-rs = "0.2.0"
pyo3 = { version = "0.23.5", features = ["extension-module"] }
rayon = "1.11.0"
regex = "1"
rustc-hash = "2.1.1"
vtkio = { git = "https://github.com/elrnv/vtkio", branch = "release-0.7" }

[features]
# Debuging feature to print statements
# if activated
# default = ["blosc"]
uPPPP_debug = []
uPPPP_warning = []
python = []
blosc = []
# [profile.dev]##opt-level = 0              # Use slightly better optimizations.

[profile.release]
incremental = true
debug = true
lto = "fat"

[profile.dev]
debug = 1
