name: Check Python documentation
# TODO test this works using act

on:
  pull_request:
    paths:
    - up4/docs/**
    - .github/workflows/docs-check-python.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: up4/docs

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python and Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          channels: "conda-forge,anaconda"
          activate-environment: testenv
      
      - name: Install mamba
        run: |
            # hdf5 version 1.14 not currently supported yet so we restrict hdf5 to 1.13 at most
            echo "hdf5<=1.13" > $CONDA_PREFIX/conda-meta/pinned
            conda install -y -c conda-forge mamba

      - name: Install Python dependencies
        run: |
          mamba install -y -c conda-forge --file requirements.txt
      - name: Build Python documentation
        env:
          SPHINXOPTS: -W
        run: make html